/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdvertisementCreateIn
 */
export interface AdvertisementCreateIn {
    /**
     * 広告名(管理用)
     * @type {string}
     * @memberof AdvertisementCreateIn
     */
    name: string;
    /**
     * URL
     * @type {string}
     * @memberof AdvertisementCreateIn
     */
    url: string;
}

/**
 * Check if a given object implements the AdvertisementCreateIn interface.
 */
export function instanceOfAdvertisementCreateIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function AdvertisementCreateInFromJSON(json: any): AdvertisementCreateIn {
    return AdvertisementCreateInFromJSONTyped(json, false);
}

export function AdvertisementCreateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvertisementCreateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function AdvertisementCreateInToJSON(value?: AdvertisementCreateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

