/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const AppRoutersManageQuestionsGetQuestionListOrdering = {
    Id: 'id',
    IdDesc: 'id_desc',
    CreatedAt: 'created_at',
    CreatedAtDesc: 'created_at_desc',
    UpdatedAt: 'updated_at',
    UpdatedAtDesc: 'updated_at_desc',
    Title: 'title',
    TitleDesc: 'title_desc'
} as const;
export type AppRoutersManageQuestionsGetQuestionListOrdering = typeof AppRoutersManageQuestionsGetQuestionListOrdering[keyof typeof AppRoutersManageQuestionsGetQuestionListOrdering];


export function AppRoutersManageQuestionsGetQuestionListOrderingFromJSON(json: any): AppRoutersManageQuestionsGetQuestionListOrdering {
    return AppRoutersManageQuestionsGetQuestionListOrderingFromJSONTyped(json, false);
}

export function AppRoutersManageQuestionsGetQuestionListOrderingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoutersManageQuestionsGetQuestionListOrdering {
    return json as AppRoutersManageQuestionsGetQuestionListOrdering;
}

export function AppRoutersManageQuestionsGetQuestionListOrderingToJSON(value?: AppRoutersManageQuestionsGetQuestionListOrdering | null): any {
    return value as any;
}

