/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const AppRoutersManageJobsGetJobFavoriteUserListAccessType = {
    Staff: 'staff',
    Agent: 'agent'
} as const;
export type AppRoutersManageJobsGetJobFavoriteUserListAccessType = typeof AppRoutersManageJobsGetJobFavoriteUserListAccessType[keyof typeof AppRoutersManageJobsGetJobFavoriteUserListAccessType];


export function AppRoutersManageJobsGetJobFavoriteUserListAccessTypeFromJSON(json: any): AppRoutersManageJobsGetJobFavoriteUserListAccessType {
    return AppRoutersManageJobsGetJobFavoriteUserListAccessTypeFromJSONTyped(json, false);
}

export function AppRoutersManageJobsGetJobFavoriteUserListAccessTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoutersManageJobsGetJobFavoriteUserListAccessType {
    return json as AppRoutersManageJobsGetJobFavoriteUserListAccessType;
}

export function AppRoutersManageJobsGetJobFavoriteUserListAccessTypeToJSON(value?: AppRoutersManageJobsGetJobFavoriteUserListAccessType | null): any {
    return value as any;
}

