/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSchemasManageQuestionsQuastionCreateInTestCaseIn
 */
export interface AppSchemasManageQuestionsQuastionCreateInTestCaseIn {
    /**
     * タイトル
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    title?: string;
    /**
     * サンプルケースか
     * @type {boolean}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    isSampleCase: boolean;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    order: number;
    /**
     * 説明文
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    description?: string;
    /**
     * 説明英語
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    descriptionEn?: string;
    /**
     * 入力値
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    stdin: string;
    /**
     * 出力値
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInTestCaseIn
     */
    stdout: string;
}

/**
 * Check if a given object implements the AppSchemasManageQuestionsQuastionCreateInTestCaseIn interface.
 */
export function instanceOfAppSchemasManageQuestionsQuastionCreateInTestCaseIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isSampleCase" in value;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "stdin" in value;
    isInstance = isInstance && "stdout" in value;

    return isInstance;
}

export function AppSchemasManageQuestionsQuastionCreateInTestCaseInFromJSON(json: any): AppSchemasManageQuestionsQuastionCreateInTestCaseIn {
    return AppSchemasManageQuestionsQuastionCreateInTestCaseInFromJSONTyped(json, false);
}

export function AppSchemasManageQuestionsQuastionCreateInTestCaseInFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasManageQuestionsQuastionCreateInTestCaseIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'isSampleCase': json['isSampleCase'],
        'order': json['order'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'descriptionEn': !exists(json, 'descriptionEn') ? undefined : json['descriptionEn'],
        'stdin': json['stdin'],
        'stdout': json['stdout'],
    };
}

export function AppSchemasManageQuestionsQuastionCreateInTestCaseInToJSON(value?: AppSchemasManageQuestionsQuastionCreateInTestCaseIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'isSampleCase': value.isSampleCase,
        'order': value.order,
        'description': value.description,
        'descriptionEn': value.descriptionEn,
        'stdin': value.stdin,
        'stdout': value.stdout,
    };
}

