/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOut } from './AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOut';
import {
    AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOutFromJSON,
    AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOutFromJSONTyped,
    AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOutToJSON,
} from './AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOut';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
} from './ContentType';
import type { ForGeneralUserQuestionContentOut } from './ForGeneralUserQuestionContentOut';
import {
    ForGeneralUserQuestionContentOutFromJSON,
    ForGeneralUserQuestionContentOutFromJSONTyped,
    ForGeneralUserQuestionContentOutToJSON,
} from './ForGeneralUserQuestionContentOut';

/**
 * 
 * @export
 * @interface AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
 */
export interface AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut {
    /**
     * コンテンツID
     * @type {number}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentCategoryName: string;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentTopicName: string;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentDivisionLabel: string;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentTypeLabel: string;
    /**
     * 
     * @type {ContentType}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentType: ContentType;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    contentTagNames?: Array<string> | null;
    /**
     * コンテンツタイトル
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    title: string;
    /**
     * 英語コンテンツタイトル
     * @type {string}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    titleEn: string;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    difficulty: number;
    /**
     * 
     * @type {ForGeneralUserQuestionContentOut}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    question?: ForGeneralUserQuestionContentOut | null;
    /**
     * 
     * @type {AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOut}
     * @memberof AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut
     */
    educationalMaterial?: AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOut | null;
}

/**
 * Check if a given object implements the AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut interface.
 */
export function instanceOfAppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "contentCategoryName" in value;
    isInstance = isInstance && "contentTopicName" in value;
    isInstance = isInstance && "contentDivisionLabel" in value;
    isInstance = isInstance && "contentTypeLabel" in value;
    isInstance = isInstance && "contentType" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "titleEn" in value;
    isInstance = isInstance && "difficulty" in value;

    return isInstance;
}

export function AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOutFromJSON(json: any): AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut {
    return AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOutFromJSONTyped(json, false);
}

export function AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contentCategoryName': json['contentCategoryName'],
        'contentTopicName': json['contentTopicName'],
        'contentDivisionLabel': json['contentDivisionLabel'],
        'contentTypeLabel': json['contentTypeLabel'],
        'contentType': ContentTypeFromJSON(json['contentType']),
        'contentTagNames': !exists(json, 'contentTagNames') ? undefined : json['contentTagNames'],
        'title': json['title'],
        'titleEn': json['titleEn'],
        'difficulty': json['difficulty'],
        'question': !exists(json, 'question') ? undefined : ForGeneralUserQuestionContentOutFromJSON(json['question']),
        'educationalMaterial': !exists(json, 'educationalMaterial') ? undefined : AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOutFromJSON(json['educationalMaterial']),
    };
}

export function AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOutToJSON(value?: AppSchemasGeneralSessionsGeneralSessionContentListOutContentDetailOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'contentCategoryName': value.contentCategoryName,
        'contentTopicName': value.contentTopicName,
        'contentDivisionLabel': value.contentDivisionLabel,
        'contentTypeLabel': value.contentTypeLabel,
        'contentType': ContentTypeToJSON(value.contentType),
        'contentTagNames': value.contentTagNames,
        'title': value.title,
        'titleEn': value.titleEn,
        'difficulty': value.difficulty,
        'question': ForGeneralUserQuestionContentOutToJSON(value.question),
        'educationalMaterial': AppSchemasGeneralSessionsGeneralSessionContentListOutEducationalMaterialOutToJSON(value.educationalMaterial),
    };
}

