/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineIn } from './AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineIn';
import {
    AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineInFromJSON,
    AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineInFromJSONTyped,
    AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineInToJSON,
} from './AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineIn';

/**
 * 
 * @export
 * @interface AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn
 */
export interface AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn {
    /**
     * ソースコード
     * @type {string}
     * @memberof AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn
     */
    sourceCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn
     */
    pgLangId: number;
    /**
     * 編集不可行
     * @type {Array<AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineIn>}
     * @memberof AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn
     */
    questionTemplateInvalidLines?: Array<AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineIn>;
}

/**
 * Check if a given object implements the AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn interface.
 */
export function instanceOfAppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pgLangId" in value;

    return isInstance;
}

export function AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInFromJSON(json: any): AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn {
    return AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInFromJSONTyped(json, false);
}

export function AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceCode': !exists(json, 'sourceCode') ? undefined : json['sourceCode'],
        'pgLangId': json['pgLangId'],
        'questionTemplateInvalidLines': !exists(json, 'questionTemplateInvalidLines') ? undefined : ((json['questionTemplateInvalidLines'] as Array<any>).map(AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineInFromJSON)),
    };
}

export function AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInToJSON(value?: AppSchemasManageQuestionsQuastionCreateInQuestionTemplateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceCode': value.sourceCode,
        'pgLangId': value.pgLangId,
        'questionTemplateInvalidLines': value.questionTemplateInvalidLines === undefined ? undefined : ((value.questionTemplateInvalidLines as Array<any>).map(AppSchemasManageQuestionsQuastionCreateInQuestionTemplateInvalidLineInToJSON)),
    };
}

