/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 使用可能PG言語
 * @export
 * @interface AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages
 */
export interface AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages {
    /**
     * 
     * @type {number}
     * @memberof AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages
     */
    name: string;
}

/**
 * Check if a given object implements the AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages interface.
 */
export function instanceOfAppSchemasManageSessionsSessionDetailOutAvailablePgLanguages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AppSchemasManageSessionsSessionDetailOutAvailablePgLanguagesFromJSON(json: any): AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages {
    return AppSchemasManageSessionsSessionDetailOutAvailablePgLanguagesFromJSONTyped(json, false);
}

export function AppSchemasManageSessionsSessionDetailOutAvailablePgLanguagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function AppSchemasManageSessionsSessionDetailOutAvailablePgLanguagesToJSON(value?: AppSchemasManageSessionsSessionDetailOutAvailablePgLanguages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

