/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut
 */
export interface AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut {
    /**
     * 順位
     * @type {number}
     * @memberof AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut
     */
    rank: number;
    /**
     * チーム名 or 表示名
     * @type {string}
     * @memberof AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut
     */
    name: string;
    /**
     * スコア
     * @type {number}
     * @memberof AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut
     */
    score: number;
}

/**
 * Check if a given object implements the AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut interface.
 */
export function instanceOfAppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rank" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOutFromJSON(json: any): AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut {
    return AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOutFromJSONTyped(json, false);
}

export function AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'name': json['name'],
        'score': json['score'],
    };
}

export function AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOutToJSON(value?: AppSchemasGeneralSessionsTechthonTechthonRankingOutTechthonRankingOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rank': value.rank,
        'name': value.name,
        'score': value.score,
    };
}

