/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificateExamTimerOut
 */
export interface CertificateExamTimerOut {
    /**
     * セッションID
     * @type {number}
     * @memberof CertificateExamTimerOut
     */
    sessionId: number;
    /**
     * ユーザーID
     * @type {number}
     * @memberof CertificateExamTimerOut
     */
    userId: number;
    /**
     * タイマー開始時間(JST)
     * @type {Date}
     * @memberof CertificateExamTimerOut
     */
    userStartAt: Date;
    /**
     * タイマー終了時間(JST)
     * @type {Date}
     * @memberof CertificateExamTimerOut
     */
    userEndAt?: Date | null;
    /**
     * 検定試験時間(分)
     * @type {number}
     * @memberof CertificateExamTimerOut
     */
    timeLimit: number;
}

/**
 * Check if a given object implements the CertificateExamTimerOut interface.
 */
export function instanceOfCertificateExamTimerOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "userStartAt" in value;
    isInstance = isInstance && "timeLimit" in value;

    return isInstance;
}

export function CertificateExamTimerOutFromJSON(json: any): CertificateExamTimerOut {
    return CertificateExamTimerOutFromJSONTyped(json, false);
}

export function CertificateExamTimerOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateExamTimerOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'userId': json['userId'],
        'userStartAt': (new Date(json['userStartAt'])),
        'userEndAt': !exists(json, 'userEndAt') ? undefined : (json['userEndAt'] === null ? null : new Date(json['userEndAt'])),
        'timeLimit': json['timeLimit'],
    };
}

export function CertificateExamTimerOutToJSON(value?: CertificateExamTimerOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionId': value.sessionId,
        'userId': value.userId,
        'userStartAt': (value.userStartAt.toISOString()),
        'userEndAt': value.userEndAt === undefined ? undefined : (value.userEndAt === null ? null : value.userEndAt.toISOString()),
        'timeLimit': value.timeLimit,
    };
}

