/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyIndustryUpdateIn
 */
export interface CompanyIndustryUpdateIn {
    /**
     * 業種ID
     * @type {number}
     * @memberof CompanyIndustryUpdateIn
     */
    id: number;
}

/**
 * Check if a given object implements the CompanyIndustryUpdateIn interface.
 */
export function instanceOfCompanyIndustryUpdateIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CompanyIndustryUpdateInFromJSON(json: any): CompanyIndustryUpdateIn {
    return CompanyIndustryUpdateInFromJSONTyped(json, false);
}

export function CompanyIndustryUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyIndustryUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CompanyIndustryUpdateInToJSON(value?: CompanyIndustryUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

