/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * コンテンツカテゴリタイプ
 * @export
 */
export const ContentCategoryType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type ContentCategoryType = typeof ContentCategoryType[keyof typeof ContentCategoryType];


export function ContentCategoryTypeFromJSON(json: any): ContentCategoryType {
    return ContentCategoryTypeFromJSONTyped(json, false);
}

export function ContentCategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentCategoryType {
    return json as ContentCategoryType;
}

export function ContentCategoryTypeToJSON(value?: ContentCategoryType | null): any {
    return value as any;
}

