/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * コンテンツパッケージレベル
 * @export
 */
export const ContentPackageLevel = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type ContentPackageLevel = typeof ContentPackageLevel[keyof typeof ContentPackageLevel];


export function ContentPackageLevelFromJSON(json: any): ContentPackageLevel {
    return ContentPackageLevelFromJSONTyped(json, false);
}

export function ContentPackageLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentPackageLevel {
    return json as ContentPackageLevel;
}

export function ContentPackageLevelToJSON(value?: ContentPackageLevel | null): any {
    return value as any;
}

