/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryUpdateIn
 */
export interface CountryUpdateIn {
    /**
     * 
     * @type {string}
     * @memberof CountryUpdateIn
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CountryUpdateIn
     */
    code?: string | null;
}

/**
 * Check if a given object implements the CountryUpdateIn interface.
 */
export function instanceOfCountryUpdateIn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CountryUpdateInFromJSON(json: any): CountryUpdateIn {
    return CountryUpdateInFromJSONTyped(json, false);
}

export function CountryUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function CountryUpdateInToJSON(value?: CountryUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'code': value.code,
    };
}

