/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHeatmapSampleCaseIn
 */
export interface CreateHeatmapSampleCaseIn {
    /**
     * ユーザー名
     * @type {string}
     * @memberof CreateHeatmapSampleCaseIn
     */
    username: string;
    /**
     * 管理用タイトル
     * @type {string}
     * @memberof CreateHeatmapSampleCaseIn
     */
    managementTitle: string;
    /**
     * 表示用タイトル
     * @type {string}
     * @memberof CreateHeatmapSampleCaseIn
     */
    displayTitle: string;
    /**
     * 業界IDリスト
     * @type {Array<number>}
     * @memberof CreateHeatmapSampleCaseIn
     */
    industries?: Array<number>;
    /**
     * 職種IDリスト
     * @type {Array<number>}
     * @memberof CreateHeatmapSampleCaseIn
     */
    occupations?: Array<number>;
}

/**
 * Check if a given object implements the CreateHeatmapSampleCaseIn interface.
 */
export function instanceOfCreateHeatmapSampleCaseIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "managementTitle" in value;
    isInstance = isInstance && "displayTitle" in value;

    return isInstance;
}

export function CreateHeatmapSampleCaseInFromJSON(json: any): CreateHeatmapSampleCaseIn {
    return CreateHeatmapSampleCaseInFromJSONTyped(json, false);
}

export function CreateHeatmapSampleCaseInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHeatmapSampleCaseIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'managementTitle': json['managementTitle'],
        'displayTitle': json['displayTitle'],
        'industries': !exists(json, 'industries') ? undefined : json['industries'],
        'occupations': !exists(json, 'occupations') ? undefined : json['occupations'],
    };
}

export function CreateHeatmapSampleCaseInToJSON(value?: CreateHeatmapSampleCaseIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'managementTitle': value.managementTitle,
        'displayTitle': value.displayTitle,
        'industries': value.industries,
        'occupations': value.occupations,
    };
}

