/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { QuitReasonType } from './QuitReasonType';
import {
    QuitReasonTypeFromJSON,
    QuitReasonTypeFromJSONTyped,
    QuitReasonTypeToJSON,
} from './QuitReasonType';

/**
 * 
 * @export
 * @interface DeleteUserIn
 */
export interface DeleteUserIn {
    /**
     * 退会理由種別
     * @type {Array<QuitReasonType>}
     * @memberof DeleteUserIn
     */
    quitReasonTypes: Array<QuitReasonType>;
    /**
     * 退会理由
     * @type {string}
     * @memberof DeleteUserIn
     */
    quitReason: string;
}

/**
 * Check if a given object implements the DeleteUserIn interface.
 */
export function instanceOfDeleteUserIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quitReasonTypes" in value;
    isInstance = isInstance && "quitReason" in value;

    return isInstance;
}

export function DeleteUserInFromJSON(json: any): DeleteUserIn {
    return DeleteUserInFromJSONTyped(json, false);
}

export function DeleteUserInFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quitReasonTypes': ((json['quitReasonTypes'] as Array<any>).map(QuitReasonTypeFromJSON)),
        'quitReason': json['quitReason'],
    };
}

export function DeleteUserInToJSON(value?: DeleteUserIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quitReasonTypes': ((value.quitReasonTypes as Array<any>).map(QuitReasonTypeToJSON)),
        'quitReason': value.quitReason,
    };
}

