/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 企業における雇用管理に関する状況
 * @export
 */
export const EmploymentManagementStatusItem = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type EmploymentManagementStatusItem = typeof EmploymentManagementStatusItem[keyof typeof EmploymentManagementStatusItem];


export function EmploymentManagementStatusItemFromJSON(json: any): EmploymentManagementStatusItem {
    return EmploymentManagementStatusItemFromJSONTyped(json, false);
}

export function EmploymentManagementStatusItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmploymentManagementStatusItem {
    return json as EmploymentManagementStatusItem;
}

export function EmploymentManagementStatusItemToJSON(value?: EmploymentManagementStatusItem | null): any {
    return value as any;
}

