/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResult } from './AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResult';
import {
    AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResultFromJSON,
    AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResultFromJSONTyped,
    AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResultToJSON,
} from './AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResult';
import type { QuestionAnswerResult } from './QuestionAnswerResult';
import {
    QuestionAnswerResultFromJSON,
    QuestionAnswerResultFromJSONTyped,
    QuestionAnswerResultToJSON,
} from './QuestionAnswerResult';
import type { Scores } from './Scores';
import {
    ScoresFromJSON,
    ScoresFromJSONTyped,
    ScoresToJSON,
} from './Scores';

/**
 * 
 * @export
 * @interface GetSessionTestCaseResultsOut
 */
export interface GetSessionTestCaseResultsOut {
    /**
     * テストケース結果
     * @type {Array<AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResult>}
     * @memberof GetSessionTestCaseResultsOut
     */
    testCaseResults: Array<AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResult>;
    /**
     * 合格テストケース数
     * @type {number}
     * @memberof GetSessionTestCaseResultsOut
     */
    passedTestCaseCount?: number | null;
    /**
     * 全テストケース数
     * @type {number}
     * @memberof GetSessionTestCaseResultsOut
     */
    totalTestCaseCount?: number | null;
    /**
     * 
     * @type {QuestionAnswerResult}
     * @memberof GetSessionTestCaseResultsOut
     */
    resultStatus: QuestionAnswerResult;
    /**
     * 
     * @type {Scores}
     * @memberof GetSessionTestCaseResultsOut
     */
    scores?: Scores | null;
}

/**
 * Check if a given object implements the GetSessionTestCaseResultsOut interface.
 */
export function instanceOfGetSessionTestCaseResultsOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "testCaseResults" in value;
    isInstance = isInstance && "resultStatus" in value;

    return isInstance;
}

export function GetSessionTestCaseResultsOutFromJSON(json: any): GetSessionTestCaseResultsOut {
    return GetSessionTestCaseResultsOutFromJSONTyped(json, false);
}

export function GetSessionTestCaseResultsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionTestCaseResultsOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testCaseResults': ((json['testCaseResults'] as Array<any>).map(AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResultFromJSON)),
        'passedTestCaseCount': !exists(json, 'passedTestCaseCount') ? undefined : json['passedTestCaseCount'],
        'totalTestCaseCount': !exists(json, 'totalTestCaseCount') ? undefined : json['totalTestCaseCount'],
        'resultStatus': QuestionAnswerResultFromJSON(json['resultStatus']),
        'scores': !exists(json, 'scores') ? undefined : ScoresFromJSON(json['scores']),
    };
}

export function GetSessionTestCaseResultsOutToJSON(value?: GetSessionTestCaseResultsOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testCaseResults': ((value.testCaseResults as Array<any>).map(AppSchemasGeneralSessionsGetSessionQuestionTestCaseResultsOutTestCaseResultToJSON)),
        'passedTestCaseCount': value.passedTestCaseCount,
        'totalTestCaseCount': value.totalTestCaseCount,
        'resultStatus': QuestionAnswerResultToJSON(value.resultStatus),
        'scores': ScoresToJSON(value.scores),
    };
}

