/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntentionalityChoicesOut
 */
export interface IntentionalityChoicesOut {
    /**
     * 
     * @type {number}
     * @memberof IntentionalityChoicesOut
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IntentionalityChoicesOut
     */
    name: string;
}

/**
 * Check if a given object implements the IntentionalityChoicesOut interface.
 */
export function instanceOfIntentionalityChoicesOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function IntentionalityChoicesOutFromJSON(json: any): IntentionalityChoicesOut {
    return IntentionalityChoicesOutFromJSONTyped(json, false);
}

export function IntentionalityChoicesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntentionalityChoicesOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function IntentionalityChoicesOutToJSON(value?: IntentionalityChoicesOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

