/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobContentOut
 */
export interface JobContentOut {
    /**
     * タイトル
     * @type {string}
     * @memberof JobContentOut
     */
    title: string;
    /**
     * 内容
     * @type {string}
     * @memberof JobContentOut
     */
    text: string;
    /**
     * 並び順
     * @type {number}
     * @memberof JobContentOut
     */
    order: number;
}

/**
 * Check if a given object implements the JobContentOut interface.
 */
export function instanceOfJobContentOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "text" in value;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function JobContentOutFromJSON(json: any): JobContentOut {
    return JobContentOutFromJSONTyped(json, false);
}

export function JobContentOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobContentOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'text': json['text'],
        'order': json['order'],
    };
}

export function JobContentOutToJSON(value?: JobContentOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'text': value.text,
        'order': value.order,
    };
}

