/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JobFeatureCategory } from './JobFeatureCategory';
import {
    JobFeatureCategoryFromJSON,
    JobFeatureCategoryFromJSONTyped,
    JobFeatureCategoryToJSON,
} from './JobFeatureCategory';

/**
 * 
 * @export
 * @interface JobFeatureUpdateIn
 */
export interface JobFeatureUpdateIn {
    /**
     * 
     * @type {string}
     * @memberof JobFeatureUpdateIn
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobFeatureUpdateIn
     */
    isForFullTimeStaff?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobFeatureUpdateIn
     */
    isForNewGraduate?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobFeatureUpdateIn
     */
    isForPartTimeJob?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobFeatureUpdateIn
     */
    isForIntern?: boolean | null;
    /**
     * 
     * @type {JobFeatureCategory}
     * @memberof JobFeatureUpdateIn
     */
    jobFeatureCategory?: JobFeatureCategory | null;
}

/**
 * Check if a given object implements the JobFeatureUpdateIn interface.
 */
export function instanceOfJobFeatureUpdateIn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JobFeatureUpdateInFromJSON(json: any): JobFeatureUpdateIn {
    return JobFeatureUpdateInFromJSONTyped(json, false);
}

export function JobFeatureUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobFeatureUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isForFullTimeStaff': !exists(json, 'isForFullTimeStaff') ? undefined : json['isForFullTimeStaff'],
        'isForNewGraduate': !exists(json, 'isForNewGraduate') ? undefined : json['isForNewGraduate'],
        'isForPartTimeJob': !exists(json, 'isForPartTimeJob') ? undefined : json['isForPartTimeJob'],
        'isForIntern': !exists(json, 'isForIntern') ? undefined : json['isForIntern'],
        'jobFeatureCategory': !exists(json, 'jobFeatureCategory') ? undefined : JobFeatureCategoryFromJSON(json['jobFeatureCategory']),
    };
}

export function JobFeatureUpdateInToJSON(value?: JobFeatureUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'isForFullTimeStaff': value.isForFullTimeStaff,
        'isForNewGraduate': value.isForNewGraduate,
        'isForPartTimeJob': value.isForPartTimeJob,
        'isForIntern': value.isForIntern,
        'jobFeatureCategory': JobFeatureCategoryToJSON(value.jobFeatureCategory),
    };
}

