/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppSchemasManageJobUsersJobUsersListOutUserListOut } from './AppSchemasManageJobUsersJobUsersListOutUserListOut';
import {
    AppSchemasManageJobUsersJobUsersListOutUserListOutFromJSON,
    AppSchemasManageJobUsersJobUsersListOutUserListOutFromJSONTyped,
    AppSchemasManageJobUsersJobUsersListOutUserListOutToJSON,
} from './AppSchemasManageJobUsersJobUsersListOutUserListOut';

/**
 * 
 * @export
 * @interface JobUserListOut
 */
export interface JobUserListOut {
    /**
     * 全件数
     * @type {number}
     * @memberof JobUserListOut
     */
    totalCount: number;
    /**
     * 検索結果件数
     * @type {number}
     * @memberof JobUserListOut
     */
    searchResultsCount: number;
    /**
     * 前データが存在するか
     * @type {boolean}
     * @memberof JobUserListOut
     */
    hasPrevious: boolean;
    /**
     * 次データが存在するか
     * @type {boolean}
     * @memberof JobUserListOut
     */
    hasNext: boolean;
    /**
     * ユーザーリスト
     * @type {Array<AppSchemasManageJobUsersJobUsersListOutUserListOut>}
     * @memberof JobUserListOut
     */
    userList: Array<AppSchemasManageJobUsersJobUsersListOutUserListOut>;
}

/**
 * Check if a given object implements the JobUserListOut interface.
 */
export function instanceOfJobUserListOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "searchResultsCount" in value;
    isInstance = isInstance && "hasPrevious" in value;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "userList" in value;

    return isInstance;
}

export function JobUserListOutFromJSON(json: any): JobUserListOut {
    return JobUserListOutFromJSONTyped(json, false);
}

export function JobUserListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobUserListOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'searchResultsCount': json['searchResultsCount'],
        'hasPrevious': json['hasPrevious'],
        'hasNext': json['hasNext'],
        'userList': ((json['userList'] as Array<any>).map(AppSchemasManageJobUsersJobUsersListOutUserListOutFromJSON)),
    };
}

export function JobUserListOutToJSON(value?: JobUserListOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalCount': value.totalCount,
        'searchResultsCount': value.searchResultsCount,
        'hasPrevious': value.hasPrevious,
        'hasNext': value.hasNext,
        'userList': ((value.userList as Array<any>).map(AppSchemasManageJobUsersJobUsersListOutUserListOutToJSON)),
    };
}

