/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OwnEventListSessionOut } from './OwnEventListSessionOut';
import {
    OwnEventListSessionOutFromJSON,
    OwnEventListSessionOutFromJSONTyped,
    OwnEventListSessionOutToJSON,
} from './OwnEventListSessionOut';

/**
 * 
 * @export
 * @interface OwnEventListDetailOut
 */
export interface OwnEventListDetailOut {
    /**
     * 
     * @type {number}
     * @memberof OwnEventListDetailOut
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof OwnEventListDetailOut
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    purposeLabel: string;
    /**
     * 主催者
     * @type {string}
     * @memberof OwnEventListDetailOut
     */
    hostName: string;
    /**
     * セッション数
     * @type {number}
     * @memberof OwnEventListDetailOut
     */
    sessionCount: number;
    /**
     * セッションが1つ以上あり、すべてのセッションが終了している
     * @type {boolean}
     * @memberof OwnEventListDetailOut
     */
    isFinished: boolean;
    /**
     * 
     * @type {Array<OwnEventListSessionOut>}
     * @memberof OwnEventListDetailOut
     */
    sessions: Array<OwnEventListSessionOut>;
}

/**
 * Check if a given object implements the OwnEventListDetailOut interface.
 */
export function instanceOfOwnEventListDetailOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "purposeLabel" in value;
    isInstance = isInstance && "hostName" in value;
    isInstance = isInstance && "sessionCount" in value;
    isInstance = isInstance && "isFinished" in value;
    isInstance = isInstance && "sessions" in value;

    return isInstance;
}

export function OwnEventListDetailOutFromJSON(json: any): OwnEventListDetailOut {
    return OwnEventListDetailOutFromJSONTyped(json, false);
}

export function OwnEventListDetailOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnEventListDetailOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'name': json['name'],
        'description': json['description'],
        'image': json['image'],
        'purposeLabel': json['purposeLabel'],
        'hostName': json['hostName'],
        'sessionCount': json['sessionCount'],
        'isFinished': json['isFinished'],
        'sessions': ((json['sessions'] as Array<any>).map(OwnEventListSessionOutFromJSON)),
    };
}

export function OwnEventListDetailOutToJSON(value?: OwnEventListDetailOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'createdBy': value.createdBy,
        'name': value.name,
        'description': value.description,
        'image': value.image,
        'purposeLabel': value.purposeLabel,
        'hostName': value.hostName,
        'sessionCount': value.sessionCount,
        'isFinished': value.isFinished,
        'sessions': ((value.sessions as Array<any>).map(OwnEventListSessionOutToJSON)),
    };
}

