/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SessionStatus } from './SessionStatus';
import {
    SessionStatusFromJSON,
    SessionStatusFromJSONTyped,
    SessionStatusToJSON,
} from './SessionStatus';

/**
 * 
 * @export
 * @interface OwnEventListSessionOut
 */
export interface OwnEventListSessionOut {
    /**
     * 
     * @type {number}
     * @memberof OwnEventListSessionOut
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof OwnEventListSessionOut
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListSessionOut
     */
    name: string;
    /**
     * セッション開始日時
     * @type {Date}
     * @memberof OwnEventListSessionOut
     */
    startsAt: Date;
    /**
     * セッション終了日時
     * @type {Date}
     * @memberof OwnEventListSessionOut
     */
    endsAt: Date;
    /**
     * イベント参加人数
     * @type {number}
     * @memberof OwnEventListSessionOut
     */
    userCount: number;
    /**
     * 
     * @type {SessionStatus}
     * @memberof OwnEventListSessionOut
     */
    sessionStatus: SessionStatus;
    /**
     * 
     * @type {string}
     * @memberof OwnEventListSessionOut
     */
    sessionStatusLabel: string;
    /**
     * セッションが終了している
     * @type {boolean}
     * @memberof OwnEventListSessionOut
     */
    isFinished: boolean;
}

/**
 * Check if a given object implements the OwnEventListSessionOut interface.
 */
export function instanceOfOwnEventListSessionOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "startsAt" in value;
    isInstance = isInstance && "endsAt" in value;
    isInstance = isInstance && "userCount" in value;
    isInstance = isInstance && "sessionStatus" in value;
    isInstance = isInstance && "sessionStatusLabel" in value;
    isInstance = isInstance && "isFinished" in value;

    return isInstance;
}

export function OwnEventListSessionOutFromJSON(json: any): OwnEventListSessionOut {
    return OwnEventListSessionOutFromJSONTyped(json, false);
}

export function OwnEventListSessionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnEventListSessionOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'name': json['name'],
        'startsAt': (new Date(json['startsAt'])),
        'endsAt': (new Date(json['endsAt'])),
        'userCount': json['userCount'],
        'sessionStatus': SessionStatusFromJSON(json['sessionStatus']),
        'sessionStatusLabel': json['sessionStatusLabel'],
        'isFinished': json['isFinished'],
    };
}

export function OwnEventListSessionOutToJSON(value?: OwnEventListSessionOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'name': value.name,
        'startsAt': (value.startsAt.toISOString()),
        'endsAt': (value.endsAt.toISOString()),
        'userCount': value.userCount,
        'sessionStatus': SessionStatusToJSON(value.sessionStatus),
        'sessionStatusLabel': value.sessionStatusLabel,
        'isFinished': value.isFinished,
    };
}

