/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 集合場所における受動喫煙防止の取り組み
 * @export
 */
export const PassiveSmokingInitiative = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type PassiveSmokingInitiative = typeof PassiveSmokingInitiative[keyof typeof PassiveSmokingInitiative];


export function PassiveSmokingInitiativeFromJSON(json: any): PassiveSmokingInitiative {
    return PassiveSmokingInitiativeFromJSONTyped(json, false);
}

export function PassiveSmokingInitiativeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassiveSmokingInitiative {
    return json as PassiveSmokingInitiative;
}

export function PassiveSmokingInitiativeToJSON(value?: PassiveSmokingInitiative | null): any {
    return value as any;
}

