/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const Permission = {
    GeneralUser: 'GENERAL_USER',
    SkillCheckUser: 'SKILL_CHECK_USER',
    ProblemView: 'PROBLEM_VIEW',
    ProblemEdit: 'PROBLEM_EDIT',
    ProblemDivisionAssign: 'PROBLEM_DIVISION_ASSIGN',
    ProblemPublish: 'PROBLEM_PUBLISH',
    ProblemSecretDifficultyAssign: 'PROBLEM_SECRET_DIFFICULTY_ASSIGN',
    ProblemSecretDifficultyEdit: 'PROBLEM_SECRET_DIFFICULTY_EDIT',
    MaterialView: 'MATERIAL_VIEW',
    MaterialEdit: 'MATERIAL_EDIT',
    ProProblemView: 'PRO_PROBLEM_VIEW',
    ProProblemEdit: 'PRO_PROBLEM_EDIT',
    ProProblemKeyAssign: 'PRO_PROBLEM_KEY_ASSIGN',
    TechthonMissionPhaseView: 'TECHTHON_MISSION_PHASE_VIEW',
    TechthonMissionPhaseEdit: 'TECHTHON_MISSION_PHASE_EDIT',
    SchoolProblemShare: 'SCHOOL_PROBLEM_SHARE',
    PrivateContentPackageView: 'PRIVATE_CONTENT_PACKAGE_VIEW',
    PublicContentPackageView: 'PUBLIC_CONTENT_PACKAGE_VIEW',
    ContentPackageEdit: 'CONTENT_PACKAGE_EDIT',
    OwnEventView: 'OWN_EVENT_VIEW',
    OwnEventEdit: 'OWN_EVENT_EDIT',
    AllEventAndSessionView: 'ALL_EVENT_AND_SESSION_VIEW',
    AllEventAndSessionEdit: 'ALL_EVENT_AND_SESSION_EDIT',
    EventSponsorAssign: 'EVENT_SPONSOR_ASSIGN',
    OwnSessionView: 'OWN_SESSION_VIEW',
    OwnSessionEdit: 'OWN_SESSION_EDIT',
    ProSessionView: 'PRO_SESSION_VIEW',
    ProSessionEdit: 'PRO_SESSION_EDIT',
    TechthonSessionView: 'TECHTHON_SESSION_VIEW',
    TechthonSessionEdit: 'TECHTHON_SESSION_EDIT',
    OwnSessionPersonalInformationView: 'OWN_SESSION_PERSONAL_INFORMATION_VIEW',
    AllSessionPersonalInformationView: 'ALL_SESSION_PERSONAL_INFORMATION_VIEW',
    SessionJoinUserLimit: 'SESSION_JOIN_USER_LIMIT',
    EventPublish: 'EVENT_PUBLISH',
    OwnJobView: 'OWN_JOB_VIEW',
    OwnJobEdit: 'OWN_JOB_EDIT',
    OwnJobPublishApplication: 'OWN_JOB_PUBLISH_APPLICATION',
    AllJobView: 'ALL_JOB_VIEW',
    AllJobEdit: 'ALL_JOB_EDIT',
    AllJobPublishApplication: 'ALL_JOB_PUBLISH_APPLICATION',
    JobPublishApproval: 'JOB_PUBLISH_APPROVAL',
    JobPublish: 'JOB_PUBLISH',
    Scout: 'SCOUT',
    ScoutFromEvent: 'SCOUT_FROM_EVENT',
    Selection: 'SELECTION',
    PortfolioView: 'PORTFOLIO_VIEW',
    PortfolioPersonalInformationView: 'PORTFOLIO_PERSONAL_INFORMATION_VIEW',
    OwnCompanyView: 'OWN_COMPANY_VIEW',
    OwnCompanyEdit: 'OWN_COMPANY_EDIT',
    AllCompanyView: 'ALL_COMPANY_VIEW',
    AllCompanyEdit: 'ALL_COMPANY_EDIT',
    Recruitment: 'RECRUITMENT',
    OwnAdminView: 'OWN_ADMIN_VIEW',
    OwnAdminEdit: 'OWN_ADMIN_EDIT',
    AllAdminView: 'ALL_ADMIN_VIEW',
    AllAdminEdit: 'ALL_ADMIN_EDIT',
    UserAccountEdit: 'USER_ACCOUNT_EDIT',
    SuperUserLogView: 'SUPER_USER_LOG_VIEW',
    OwnSkillCheckAccountView: 'OWN_SKILL_CHECK_ACCOUNT_VIEW',
    OwnSkillCheckAccountEdit: 'OWN_SKILL_CHECK_ACCOUNT_EDIT',
    OwnSkillCheckAccountSessionInvitation: 'OWN_SKILL_CHECK_ACCOUNT_SESSION_INVITATION',
    AllSkillCheckAccountView: 'ALL_SKILL_CHECK_ACCOUNT_VIEW',
    AllSkillCheckAccountEdit: 'ALL_SKILL_CHECK_ACCOUNT_EDIT',
    AllSkillCheckAccountSessionInvitation: 'ALL_SKILL_CHECK_ACCOUNT_SESSION_INVITATION',
    StaffView: 'STAFF_VIEW',
    StaffEdit: 'STAFF_EDIT',
    Chat: 'CHAT',
    ChatView: 'CHAT_VIEW',
    InformationView: 'INFORMATION_VIEW',
    InformationEdit: 'INFORMATION_EDIT',
    AdvertisementView: 'ADVERTISEMENT_VIEW',
    AdvertisementEdit: 'ADVERTISEMENT_EDIT',
    AssetsEdit: 'ASSETS_EDIT',
    KpiView: 'KPI_VIEW',
    AnalyticsView: 'ANALYTICS_VIEW',
    AssetsView: 'ASSETS_VIEW'
} as const;
export type Permission = typeof Permission[keyof typeof Permission];


export function PermissionFromJSON(json: any): Permission {
    return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permission {
    return json as Permission;
}

export function PermissionToJSON(value?: Permission | null): any {
    return value as any;
}

