/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PgLangSampleCodeListOut
 */
export interface PgLangSampleCodeListOut {
    /**
     * 
     * @type {number}
     * @memberof PgLangSampleCodeListOut
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PgLangSampleCodeListOut
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PgLangSampleCodeListOut
     */
    sourceCode: string;
    /**
     * 
     * @type {string}
     * @memberof PgLangSampleCodeListOut
     */
    stdin: string;
    /**
     * 
     * @type {string}
     * @memberof PgLangSampleCodeListOut
     */
    stdout: string;
}

/**
 * Check if a given object implements the PgLangSampleCodeListOut interface.
 */
export function instanceOfPgLangSampleCodeListOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "sourceCode" in value;
    isInstance = isInstance && "stdin" in value;
    isInstance = isInstance && "stdout" in value;

    return isInstance;
}

export function PgLangSampleCodeListOutFromJSON(json: any): PgLangSampleCodeListOut {
    return PgLangSampleCodeListOutFromJSONTyped(json, false);
}

export function PgLangSampleCodeListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PgLangSampleCodeListOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'sourceCode': json['sourceCode'],
        'stdin': json['stdin'],
        'stdout': json['stdout'],
    };
}

export function PgLangSampleCodeListOutToJSON(value?: PgLangSampleCodeListOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'sourceCode': value.sourceCode,
        'stdin': value.stdin,
        'stdout': value.stdout,
    };
}

