/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * プログラミング言語
 * @export
 * @interface Pglang
 */
export interface Pglang {
    /**
     * ID
     * @type {number}
     * @memberof Pglang
     */
    id: number;
    /**
     * 名前
     * @type {string}
     * @memberof Pglang
     */
    name: string;
}

/**
 * Check if a given object implements the Pglang interface.
 */
export function instanceOfPglang(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function PglangFromJSON(json: any): Pglang {
    return PglangFromJSONTyped(json, false);
}

export function PglangFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pglang {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PglangToJSON(value?: Pglang | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

