/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProQuestionFileOut
 */
export interface ProQuestionFileOut {
    /**
     * 順番
     * @type {number}
     * @memberof ProQuestionFileOut
     */
    order: number;
    /**
     * ファイル名
     * @type {string}
     * @memberof ProQuestionFileOut
     */
    name: string;
}

/**
 * Check if a given object implements the ProQuestionFileOut interface.
 */
export function instanceOfProQuestionFileOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProQuestionFileOutFromJSON(json: any): ProQuestionFileOut {
    return ProQuestionFileOutFromJSONTyped(json, false);
}

export function ProQuestionFileOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProQuestionFileOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
        'name': json['name'],
    };
}

export function ProQuestionFileOutToJSON(value?: ProQuestionFileOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
        'name': value.name,
    };
}

