/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProSessionRemaningNumOfParticipantsOut
 */
export interface ProSessionRemaningNumOfParticipantsOut {
    /**
     * 残り参加可能人数(参加チケット)
     * @type {number}
     * @memberof ProSessionRemaningNumOfParticipantsOut
     */
    remainingNumOfParticipants: number;
}

/**
 * Check if a given object implements the ProSessionRemaningNumOfParticipantsOut interface.
 */
export function instanceOfProSessionRemaningNumOfParticipantsOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "remainingNumOfParticipants" in value;

    return isInstance;
}

export function ProSessionRemaningNumOfParticipantsOutFromJSON(json: any): ProSessionRemaningNumOfParticipantsOut {
    return ProSessionRemaningNumOfParticipantsOutFromJSONTyped(json, false);
}

export function ProSessionRemaningNumOfParticipantsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProSessionRemaningNumOfParticipantsOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remainingNumOfParticipants': json['remainingNumOfParticipants'],
    };
}

export function ProSessionRemaningNumOfParticipantsOutToJSON(value?: ProSessionRemaningNumOfParticipantsOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remainingNumOfParticipants': value.remainingNumOfParticipants,
    };
}

