/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionTemplateInvalidLineDetailOut
 */
export interface QuestionTemplateInvalidLineDetailOut {
    /**
     * 開始行
     * @type {number}
     * @memberof QuestionTemplateInvalidLineDetailOut
     */
    startLine: number;
    /**
     * 終了行
     * @type {number}
     * @memberof QuestionTemplateInvalidLineDetailOut
     */
    endLine: number;
}

/**
 * Check if a given object implements the QuestionTemplateInvalidLineDetailOut interface.
 */
export function instanceOfQuestionTemplateInvalidLineDetailOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "startLine" in value;
    isInstance = isInstance && "endLine" in value;

    return isInstance;
}

export function QuestionTemplateInvalidLineDetailOutFromJSON(json: any): QuestionTemplateInvalidLineDetailOut {
    return QuestionTemplateInvalidLineDetailOutFromJSONTyped(json, false);
}

export function QuestionTemplateInvalidLineDetailOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionTemplateInvalidLineDetailOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startLine': json['startLine'],
        'endLine': json['endLine'],
    };
}

export function QuestionTemplateInvalidLineDetailOutToJSON(value?: QuestionTemplateInvalidLineDetailOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startLine': value.startLine,
        'endLine': value.endLine,
    };
}

