/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionTestCaseExecuteOut
 */
export interface QuestionTestCaseExecuteOut {
    /**
     * 問題検証結果ID
     * @type {number}
     * @memberof QuestionTestCaseExecuteOut
     */
    questionVerificationResultId: number;
}

/**
 * Check if a given object implements the QuestionTestCaseExecuteOut interface.
 */
export function instanceOfQuestionTestCaseExecuteOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "questionVerificationResultId" in value;

    return isInstance;
}

export function QuestionTestCaseExecuteOutFromJSON(json: any): QuestionTestCaseExecuteOut {
    return QuestionTestCaseExecuteOutFromJSONTyped(json, false);
}

export function QuestionTestCaseExecuteOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionTestCaseExecuteOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionVerificationResultId': json['questionVerificationResultId'],
    };
}

export function QuestionTestCaseExecuteOutToJSON(value?: QuestionTestCaseExecuteOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionVerificationResultId': value.questionVerificationResultId,
    };
}

