/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 学校の種類
 * @export
 */
export const SchoolType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15,
    NUMBER_16: 16,
    NUMBER_17: 17
} as const;
export type SchoolType = typeof SchoolType[keyof typeof SchoolType];


export function SchoolTypeFromJSON(json: any): SchoolType {
    return SchoolTypeFromJSONTyped(json, false);
}

export function SchoolTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolType {
    return json as SchoolType;
}

export function SchoolTypeToJSON(value?: SchoolType | null): any {
    return value as any;
}

