/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchoolTypeChoicesOut
 */
export interface SchoolTypeChoicesOut {
    /**
     * 
     * @type {number}
     * @memberof SchoolTypeChoicesOut
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof SchoolTypeChoicesOut
     */
    label: string;
}

/**
 * Check if a given object implements the SchoolTypeChoicesOut interface.
 */
export function instanceOfSchoolTypeChoicesOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function SchoolTypeChoicesOutFromJSON(json: any): SchoolTypeChoicesOut {
    return SchoolTypeChoicesOutFromJSONTyped(json, false);
}

export function SchoolTypeChoicesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolTypeChoicesOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'label': json['label'],
    };
}

export function SchoolTypeChoicesOutToJSON(value?: SchoolTypeChoicesOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'label': value.label,
    };
}

