/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoutAcceptanceIn
 */
export interface ScoutAcceptanceIn {
    /**
     * スカウトを受け取るか
     * @type {boolean}
     * @memberof ScoutAcceptanceIn
     */
    receiveScouts: boolean;
}

/**
 * Check if a given object implements the ScoutAcceptanceIn interface.
 */
export function instanceOfScoutAcceptanceIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "receiveScouts" in value;

    return isInstance;
}

export function ScoutAcceptanceInFromJSON(json: any): ScoutAcceptanceIn {
    return ScoutAcceptanceInFromJSONTyped(json, false);
}

export function ScoutAcceptanceInFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoutAcceptanceIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'receiveScouts': json['receiveScouts'],
    };
}

export function ScoutAcceptanceInToJSON(value?: ScoutAcceptanceIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'receiveScouts': value.receiveScouts,
    };
}

