/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectionMemoUpdateIn
 */
export interface SelectionMemoUpdateIn {
    /**
     * 選考メモ
     * @type {string}
     * @memberof SelectionMemoUpdateIn
     */
    memo?: string;
}

/**
 * Check if a given object implements the SelectionMemoUpdateIn interface.
 */
export function instanceOfSelectionMemoUpdateIn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SelectionMemoUpdateInFromJSON(json: any): SelectionMemoUpdateIn {
    return SelectionMemoUpdateInFromJSONTyped(json, false);
}

export function SelectionMemoUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionMemoUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
    };
}

export function SelectionMemoUpdateInToJSON(value?: SelectionMemoUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memo': value.memo,
    };
}

