/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SelectionDetailOut } from './SelectionDetailOut';
import {
    SelectionDetailOutFromJSON,
    SelectionDetailOutFromJSONTyped,
    SelectionDetailOutToJSON,
} from './SelectionDetailOut';

/**
 * 
 * @export
 * @interface SelectionsOut
 */
export interface SelectionsOut {
    /**
     * 総件数
     * @type {number}
     * @memberof SelectionsOut
     */
    totalCount: number;
    /**
     * 次ページ有無
     * @type {boolean}
     * @memberof SelectionsOut
     */
    hasNext: boolean;
    /**
     * 前ページ有無
     * @type {boolean}
     * @memberof SelectionsOut
     */
    hasPrevious: boolean;
    /**
     * 選考データ
     * @type {Array<SelectionDetailOut>}
     * @memberof SelectionsOut
     */
    selections: Array<SelectionDetailOut>;
}

/**
 * Check if a given object implements the SelectionsOut interface.
 */
export function instanceOfSelectionsOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "hasPrevious" in value;
    isInstance = isInstance && "selections" in value;

    return isInstance;
}

export function SelectionsOutFromJSON(json: any): SelectionsOut {
    return SelectionsOutFromJSONTyped(json, false);
}

export function SelectionsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionsOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'hasNext': json['hasNext'],
        'hasPrevious': json['hasPrevious'],
        'selections': ((json['selections'] as Array<any>).map(SelectionDetailOutFromJSON)),
    };
}

export function SelectionsOutToJSON(value?: SelectionsOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalCount': value.totalCount,
        'hasNext': value.hasNext,
        'hasPrevious': value.hasPrevious,
        'selections': ((value.selections as Array<any>).map(SelectionDetailOutToJSON)),
    };
}

