/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectionDateTimeUpdateIn
 */
export interface SelectionDateTimeUpdateIn {
    /**
     * 選考開始予定日時
     * @type {Date}
     * @memberof SelectionDateTimeUpdateIn
     */
    startsAt?: Date | null;
    /**
     * 選考終了予定日時
     * @type {Date}
     * @memberof SelectionDateTimeUpdateIn
     */
    endsAt?: Date | null;
}

/**
 * Check if a given object implements the SelectionDateTimeUpdateIn interface.
 */
export function instanceOfSelectionDateTimeUpdateIn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SelectionDateTimeUpdateInFromJSON(json: any): SelectionDateTimeUpdateIn {
    return SelectionDateTimeUpdateInFromJSONTyped(json, false);
}

export function SelectionDateTimeUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionDateTimeUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startsAt': !exists(json, 'startsAt') ? undefined : (json['startsAt'] === null ? null : new Date(json['startsAt'])),
        'endsAt': !exists(json, 'endsAt') ? undefined : (json['endsAt'] === null ? null : new Date(json['endsAt'])),
    };
}

export function SelectionDateTimeUpdateInToJSON(value?: SelectionDateTimeUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startsAt': value.startsAt === undefined ? undefined : (value.startsAt === null ? null : value.startsAt.toISOString()),
        'endsAt': value.endsAt === undefined ? undefined : (value.endsAt === null ? null : value.endsAt.toISOString()),
    };
}

