/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendJobScoutToUserIn
 */
export interface SendJobScoutToUserIn {
    /**
     * メッセージ
     * @type {string}
     * @memberof SendJobScoutToUserIn
     */
    message: string;
    /**
     * ユーザー選考管理画面URL(通知作成用)
     * @type {string}
     * @memberof SendJobScoutToUserIn
     */
    userScoutListUrl: string;
    /**
     * ユーザー選考管理画面URL(通知作成用)
     * @type {string}
     * @memberof SendJobScoutToUserIn
     */
    agentScoutManagementUrl: string;
}

/**
 * Check if a given object implements the SendJobScoutToUserIn interface.
 */
export function instanceOfSendJobScoutToUserIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "userScoutListUrl" in value;
    isInstance = isInstance && "agentScoutManagementUrl" in value;

    return isInstance;
}

export function SendJobScoutToUserInFromJSON(json: any): SendJobScoutToUserIn {
    return SendJobScoutToUserInFromJSONTyped(json, false);
}

export function SendJobScoutToUserInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendJobScoutToUserIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'userScoutListUrl': json['userScoutListUrl'],
        'agentScoutManagementUrl': json['agentScoutManagementUrl'],
    };
}

export function SendJobScoutToUserInToJSON(value?: SendJobScoutToUserIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'userScoutListUrl': value.userScoutListUrl,
        'agentScoutManagementUrl': value.agentScoutManagementUrl,
    };
}

