/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * セッションユーザーステータス
 * @export
 */
export const SessionUserStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type SessionUserStatus = typeof SessionUserStatus[keyof typeof SessionUserStatus];


export function SessionUserStatusFromJSON(json: any): SessionUserStatus {
    return SessionUserStatusFromJSONTyped(json, false);
}

export function SessionUserStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionUserStatus {
    return json as SessionUserStatus;
}

export function SessionUserStatusToJSON(value?: SessionUserStatus | null): any {
    return value as any;
}

