/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SessionListOut } from './SessionListOut';
import {
    SessionListOutFromJSON,
    SessionListOutFromJSONTyped,
    SessionListOutToJSON,
} from './SessionListOut';

/**
 * 
 * @export
 * @interface SessionListCountOut
 */
export interface SessionListCountOut {
    /**
     * 総件数
     * @type {number}
     * @memberof SessionListCountOut
     */
    count: number;
    /**
     * 
     * @type {Array<SessionListOut>}
     * @memberof SessionListCountOut
     */
    sessions: Array<SessionListOut>;
}

/**
 * Check if a given object implements the SessionListCountOut interface.
 */
export function instanceOfSessionListCountOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "sessions" in value;

    return isInstance;
}

export function SessionListCountOutFromJSON(json: any): SessionListCountOut {
    return SessionListCountOutFromJSONTyped(json, false);
}

export function SessionListCountOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionListCountOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'sessions': ((json['sessions'] as Array<any>).map(SessionListOutFromJSON)),
    };
}

export function SessionListCountOutToJSON(value?: SessionListCountOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'sessions': ((value.sessions as Array<any>).map(SessionListOutToJSON)),
    };
}

