/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionTermUpdateIn
 */
export interface SessionTermUpdateIn {
    /**
     * 規約タイトル
     * @type {string}
     * @memberof SessionTermUpdateIn
     */
    title: string;
    /**
     * 本文
     * @type {string}
     * @memberof SessionTermUpdateIn
     */
    content: string;
}

/**
 * Check if a given object implements the SessionTermUpdateIn interface.
 */
export function instanceOfSessionTermUpdateIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function SessionTermUpdateInFromJSON(json: any): SessionTermUpdateIn {
    return SessionTermUpdateInFromJSONTyped(json, false);
}

export function SessionTermUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionTermUpdateIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function SessionTermUpdateInToJSON(value?: SessionTermUpdateIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
    };
}

