/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompanyDocumentType } from './CompanyDocumentType';
import {
    CompanyDocumentTypeFromJSON,
    CompanyDocumentTypeFromJSONTyped,
    CompanyDocumentTypeToJSON,
} from './CompanyDocumentType';

/**
 * 
 * @export
 * @interface SessionCompanyDocumentListOut
 */
export interface SessionCompanyDocumentListOut {
    /**
     * 
     * @type {Date}
     * @memberof SessionCompanyDocumentListOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SessionCompanyDocumentListOut
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SessionCompanyDocumentListOut
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SessionCompanyDocumentListOut
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SessionCompanyDocumentListOut
     */
    description: string;
    /**
     * 
     * @type {CompanyDocumentType}
     * @memberof SessionCompanyDocumentListOut
     */
    companyDocumentType: CompanyDocumentType;
    /**
     * 動画/PDF
     * @type {string}
     * @memberof SessionCompanyDocumentListOut
     */
    file: string;
    /**
     * 
     * @type {number}
     * @memberof SessionCompanyDocumentListOut
     */
    companyId: number;
}

/**
 * Check if a given object implements the SessionCompanyDocumentListOut interface.
 */
export function instanceOfSessionCompanyDocumentListOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "companyDocumentType" in value;
    isInstance = isInstance && "file" in value;
    isInstance = isInstance && "companyId" in value;

    return isInstance;
}

export function SessionCompanyDocumentListOutFromJSON(json: any): SessionCompanyDocumentListOut {
    return SessionCompanyDocumentListOutFromJSONTyped(json, false);
}

export function SessionCompanyDocumentListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionCompanyDocumentListOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'companyDocumentType': CompanyDocumentTypeFromJSON(json['companyDocumentType']),
        'file': json['file'],
        'companyId': json['companyId'],
    };
}

export function SessionCompanyDocumentListOutToJSON(value?: SessionCompanyDocumentListOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'companyDocumentType': CompanyDocumentTypeToJSON(value.companyDocumentType),
        'file': value.file,
        'companyId': value.companyId,
    };
}

