/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillLevelChoicesOut
 */
export interface SkillLevelChoicesOut {
    /**
     * 
     * @type {number}
     * @memberof SkillLevelChoicesOut
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof SkillLevelChoicesOut
     */
    label: string;
}

/**
 * Check if a given object implements the SkillLevelChoicesOut interface.
 */
export function instanceOfSkillLevelChoicesOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function SkillLevelChoicesOutFromJSON(json: any): SkillLevelChoicesOut {
    return SkillLevelChoicesOutFromJSONTyped(json, false);
}

export function SkillLevelChoicesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillLevelChoicesOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'label': json['label'],
    };
}

export function SkillLevelChoicesOutToJSON(value?: SkillLevelChoicesOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'label': value.label,
    };
}

