/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SkillCheckUsersBaseOut } from './SkillCheckUsersBaseOut';
import {
    SkillCheckUsersBaseOutFromJSON,
    SkillCheckUsersBaseOutFromJSONTyped,
    SkillCheckUsersBaseOutToJSON,
} from './SkillCheckUsersBaseOut';

/**
 * 
 * @export
 * @interface SkillCheckUsersListOut
 */
export interface SkillCheckUsersListOut {
    /**
     * スキルチェックアカウント登録数
     * @type {number}
     * @memberof SkillCheckUsersListOut
     */
    currentCount: number;
    /**
     * 発行可能スキルチェックアカウント数
     * @type {number}
     * @memberof SkillCheckUsersListOut
     */
    countLimit: number;
    /**
     * 
     * @type {Array<SkillCheckUsersBaseOut>}
     * @memberof SkillCheckUsersListOut
     */
    accounts: Array<SkillCheckUsersBaseOut>;
}

/**
 * Check if a given object implements the SkillCheckUsersListOut interface.
 */
export function instanceOfSkillCheckUsersListOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currentCount" in value;
    isInstance = isInstance && "countLimit" in value;
    isInstance = isInstance && "accounts" in value;

    return isInstance;
}

export function SkillCheckUsersListOutFromJSON(json: any): SkillCheckUsersListOut {
    return SkillCheckUsersListOutFromJSONTyped(json, false);
}

export function SkillCheckUsersListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillCheckUsersListOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentCount': json['currentCount'],
        'countLimit': json['countLimit'],
        'accounts': ((json['accounts'] as Array<any>).map(SkillCheckUsersBaseOutFromJSON)),
    };
}

export function SkillCheckUsersListOutToJSON(value?: SkillCheckUsersListOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentCount': value.currentCount,
        'countLimit': value.countLimit,
        'accounts': ((value.accounts as Array<any>).map(SkillCheckUsersBaseOutToJSON)),
    };
}

