/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TechthonSkillDataOut
 */
export interface TechthonSkillDataOut {
    /**
     * コメント(サマリー)
     * @type {string}
     * @memberof TechthonSkillDataOut
     */
    comment?: string;
    /**
     * 使用プログラミング言語
     * @type {Array<number>}
     * @memberof TechthonSkillDataOut
     */
    pgLangs?: Array<number>;
    /**
     * 使用フレームワーク
     * @type {Array<number>}
     * @memberof TechthonSkillDataOut
     */
    frameworks?: Array<number>;
}

/**
 * Check if a given object implements the TechthonSkillDataOut interface.
 */
export function instanceOfTechthonSkillDataOut(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TechthonSkillDataOutFromJSON(json: any): TechthonSkillDataOut {
    return TechthonSkillDataOutFromJSONTyped(json, false);
}

export function TechthonSkillDataOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechthonSkillDataOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'pgLangs': !exists(json, 'pgLangs') ? undefined : json['pgLangs'],
        'frameworks': !exists(json, 'frameworks') ? undefined : json['frameworks'],
    };
}

export function TechthonSkillDataOutToJSON(value?: TechthonSkillDataOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'pgLangs': value.pgLangs,
        'frameworks': value.frameworks,
    };
}

