/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TechthonHintOut
 */
export interface TechthonHintOut {
    /**
     * 
     * @type {number}
     * @memberof TechthonHintOut
     */
    id: number;
    /**
     * ヒント本文
     * @type {string}
     * @memberof TechthonHintOut
     */
    content: string;
}

/**
 * Check if a given object implements the TechthonHintOut interface.
 */
export function instanceOfTechthonHintOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function TechthonHintOutFromJSON(json: any): TechthonHintOut {
    return TechthonHintOutFromJSONTyped(json, false);
}

export function TechthonHintOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechthonHintOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
    };
}

export function TechthonHintOutToJSON(value?: TechthonHintOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
    };
}

