/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TermType } from './TermType';
import {
    TermTypeFromJSON,
    TermTypeFromJSONTyped,
    TermTypeToJSON,
} from './TermType';

/**
 * 
 * @export
 * @interface TermListOut
 */
export interface TermListOut {
    /**
     * 
     * @type {number}
     * @memberof TermListOut
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof TermListOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TermListOut
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TermListOut
     */
    termTypeLabel: string;
    /**
     * 
     * @type {TermType}
     * @memberof TermListOut
     */
    termType: TermType;
    /**
     * 
     * @type {string}
     * @memberof TermListOut
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof TermListOut
     */
    contentEn: string;
    /**
     * 
     * @type {number}
     * @memberof TermListOut
     */
    version: number;
}

/**
 * Check if a given object implements the TermListOut interface.
 */
export function instanceOfTermListOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "termTypeLabel" in value;
    isInstance = isInstance && "termType" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "contentEn" in value;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function TermListOutFromJSON(json: any): TermListOut {
    return TermListOutFromJSONTyped(json, false);
}

export function TermListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TermListOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'termTypeLabel': json['termTypeLabel'],
        'termType': TermTypeFromJSON(json['termType']),
        'content': json['content'],
        'contentEn': json['contentEn'],
        'version': json['version'],
    };
}

export function TermListOutToJSON(value?: TermListOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'termTypeLabel': value.termTypeLabel,
        'termType': TermTypeToJSON(value.termType),
        'content': value.content,
        'contentEn': value.contentEn,
        'version': value.version,
    };
}

