/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VocationalAbilityStatusItem } from './VocationalAbilityStatusItem';
import {
    VocationalAbilityStatusItemFromJSON,
    VocationalAbilityStatusItemFromJSONTyped,
    VocationalAbilityStatusItemToJSON,
} from './VocationalAbilityStatusItem';

/**
 * 
 * @export
 * @interface VocationalAbilityStatusDetail
 */
export interface VocationalAbilityStatusDetail {
    /**
     * ID
     * @type {number}
     * @memberof VocationalAbilityStatusDetail
     */
    id: number;
    /**
     * 
     * @type {VocationalAbilityStatusItem}
     * @memberof VocationalAbilityStatusDetail
     */
    item: VocationalAbilityStatusItem | null;
    /**
     * 詳細
     * @type {string}
     * @memberof VocationalAbilityStatusDetail
     */
    detail: string;
}

/**
 * Check if a given object implements the VocationalAbilityStatusDetail interface.
 */
export function instanceOfVocationalAbilityStatusDetail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "item" in value;
    isInstance = isInstance && "detail" in value;

    return isInstance;
}

export function VocationalAbilityStatusDetailFromJSON(json: any): VocationalAbilityStatusDetail {
    return VocationalAbilityStatusDetailFromJSONTyped(json, false);
}

export function VocationalAbilityStatusDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): VocationalAbilityStatusDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'item': VocationalAbilityStatusItemFromJSON(json['item']),
        'detail': json['detail'],
    };
}

export function VocationalAbilityStatusDetailToJSON(value?: VocationalAbilityStatusDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'item': VocationalAbilityStatusItemToJSON(value.item),
        'detail': value.detail,
    };
}

