/* tslint:disable */
/* eslint-disable */
/**
 * TechFUL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 職業能力開発・向上に関する状況
 * @export
 */
export const VocationalAbilityStatusItem = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type VocationalAbilityStatusItem = typeof VocationalAbilityStatusItem[keyof typeof VocationalAbilityStatusItem];


export function VocationalAbilityStatusItemFromJSON(json: any): VocationalAbilityStatusItem {
    return VocationalAbilityStatusItemFromJSONTyped(json, false);
}

export function VocationalAbilityStatusItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): VocationalAbilityStatusItem {
    return json as VocationalAbilityStatusItem;
}

export function VocationalAbilityStatusItemToJSON(value?: VocationalAbilityStatusItem | null): any {
    return value as any;
}

