steps:
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: yarn
  args: ["script-lint"]
- name: node
  entrypoint: npx
  args: ["nuxi", "generate", "dist"]
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', './dist', 'gs://ci-text/']