steps:
- name: node:21
  entrypoint: npm
  args: ["install"]
- name: node:21
  entrypoint: yarn
  args: ["script-lint"]
- name: node:21
  entrypoint: npx
  args: ["nuxi", "generate", "."]
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', 'dist', 'gs://ci-text/']