version: '3.8'
services:
  # フロント本体
  scout-web:
    container_name: 'scout-web'
    build:
      context: .
      args:
        # Windowsであれば http://127.0.0.1:8016 でアクセスできる
        SCOUT_WEB_LOCAL_URL: http://localhost:8016/
        SCOUT_API_LOCAL_URL: http://localhost:1019/
      dockerfile: ./Dockerfile
    ports:
      - 8016:8016
      - 919:919
    volumes:
      - ./:/usr/src/app
      # `node_modules`までホストと同期してしまうと、特にWSL2上でのパフォーマンスに著しく影響を及ぼすので
      # 除外している
      # - node_modules_storage:/usr/src/app/node_modules
    #networks:
    #  compose-network:
    #    ipv4_address: 192.168.155.10
    tty: true
volumes:
  node_modules_storage:
#networks:
#  compose-network:
#    driver: bridge
#    external: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.155.0/16
